use core::arch::asm;

// MD5 round constants paired low-word first so one 64-bit load feeds two
// consecutive rounds on little-endian AArch64.
static K_PAIRS: [u64; 32] = [
    0xe8c7_b756_d76a_a478,
    0xc1bd_ceee_2420_70db,
    0x4787_c62a_f57c_0faf,
    0xfd46_9501_a830_4613,
    0x8b44_f7af_6980_98d8,
    0x895c_d7be_ffff_5bb1,
    0xfd98_7193_6b90_1122,
    0x49b4_0821_a679_438e,
    0xc040_b340_f61e_2562,
    0xe9b6_c7aa_265e_5a51,
    0x0244_1453_d62f_105d,
    0xe7d3_fbc8_d8a1_e681,
    0xc337_07d6_21e1_cde6,
    0x455a_14ed_f4d5_0d87,
    0xfcef_a3f8_a9e3_e905,
    0x8d2a_4c8a_676f_02d9,
    0x8771_f681_fffa_3942,
    0xfde5_380c_6d9d_6122,
    0x4bde_cfa9_a4be_ea44,
    0xbebf_bc70_f6bb_4b60,
    0xeaa1_27fa_289b_7ec6,
    0x0488_1d05_d4ef_3085,
    0xe6db_99e5_d9d4_d039,
    0xc4ac_5665_1fa2_7cf8,
    0x432a_ff97_f429_2244,
    0xfc93_a039_ab94_23a7,
    0x8f0c_cc92_655b_59c3,
    0x8584_5dd1_ffef_f47d,
    0xfe2c_e6e0_6fa8_7e4f,
    0x4e08_11a1_a301_4314,
    0xbd3a_f235_f753_7e82,
    0xeb86_d391_2ad7_d2bb,
];

/// Compress one little-endian MD5 block with an AArch64 integer kernel.
#[inline]
pub(crate) fn compress_block(state: &mut [u32; 4], block: &[u8; 64]) {
    let initial = *state;
    let [mut a, mut b, mut c, mut d] = *state;

    // SAFETY: `block` and `K_PAIRS` are valid for every read performed below. The
    // assembly only reads memory and only mutates declared register outputs.
    unsafe {
        asm!(
            "ldp {m0:w}, {m1:w}, [{input}, #0]",
            "ldp {m2:w}, {m3:w}, [{input}, #8]",
            "ldp {m4:w}, {m5:w}, [{input}, #16]",
            "ldp {m6:w}, {m7:w}, [{input}, #24]",
            "ldp {m8:w}, {m9:w}, [{input}, #32]",
            "ldp {m10:w}, {m11:w}, [{input}, #40]",
            "ldp {m12:w}, {m13:w}, [{input}, #48]",
            "ldp {m14:w}, {m15:w}, [{input}, #56]",
            "ldr {k:x}, [{constants}, #0]",
            "add {a:w}, {a:w}, {m0:w}",
            "eor {t1:w}, {c:w}, {d:w}",
            "add {a:w}, {a:w}, {k:w}",
            "and {t1:w}, {t1:w}, {b:w}",
            "eor {t1:w}, {t1:w}, {d:w}",
            "add {a:w}, {a:w}, {t1:w}",
            "ror {a:w}, {a:w}, #25",
            "add {a:w}, {a:w}, {b:w}",
            "lsr {k:x}, {k:x}, #32",
            "add {d:w}, {d:w}, {m1:w}",
            "eor {t1:w}, {b:w}, {c:w}",
            "add {d:w}, {d:w}, {k:w}",
            "and {t1:w}, {t1:w}, {a:w}",
            "eor {t1:w}, {t1:w}, {c:w}",
            "add {d:w}, {d:w}, {t1:w}",
            "ror {d:w}, {d:w}, #20",
            "add {d:w}, {d:w}, {a:w}",
            "ldr {k:x}, [{constants}, #8]",
            "add {c:w}, {c:w}, {m2:w}",
            "eor {t1:w}, {a:w}, {b:w}",
            "add {c:w}, {c:w}, {k:w}",
            "and {t1:w}, {t1:w}, {d:w}",
            "eor {t1:w}, {t1:w}, {b:w}",
            "add {c:w}, {c:w}, {t1:w}",
            "ror {c:w}, {c:w}, #15",
            "add {c:w}, {c:w}, {d:w}",
            "lsr {k:x}, {k:x}, #32",
            "add {b:w}, {b:w}, {m3:w}",
            "eor {t1:w}, {d:w}, {a:w}",
            "add {b:w}, {b:w}, {k:w}",
            "and {t1:w}, {t1:w}, {c:w}",
            "eor {t1:w}, {t1:w}, {a:w}",
            "add {b:w}, {b:w}, {t1:w}",
            "ror {b:w}, {b:w}, #10",
            "add {b:w}, {b:w}, {c:w}",
            "ldr {k:x}, [{constants}, #16]",
            "add {a:w}, {a:w}, {m4:w}",
            "eor {t1:w}, {c:w}, {d:w}",
            "add {a:w}, {a:w}, {k:w}",
            "and {t1:w}, {t1:w}, {b:w}",
            "eor {t1:w}, {t1:w}, {d:w}",
            "add {a:w}, {a:w}, {t1:w}",
            "ror {a:w}, {a:w}, #25",
            "add {a:w}, {a:w}, {b:w}",
            "lsr {k:x}, {k:x}, #32",
            "add {d:w}, {d:w}, {m5:w}",
            "eor {t1:w}, {b:w}, {c:w}",
            "add {d:w}, {d:w}, {k:w}",
            "and {t1:w}, {t1:w}, {a:w}",
            "eor {t1:w}, {t1:w}, {c:w}",
            "add {d:w}, {d:w}, {t1:w}",
            "ror {d:w}, {d:w}, #20",
            "add {d:w}, {d:w}, {a:w}",
            "ldr {k:x}, [{constants}, #24]",
            "add {c:w}, {c:w}, {m6:w}",
            "eor {t1:w}, {a:w}, {b:w}",
            "add {c:w}, {c:w}, {k:w}",
            "and {t1:w}, {t1:w}, {d:w}",
            "eor {t1:w}, {t1:w}, {b:w}",
            "add {c:w}, {c:w}, {t1:w}",
            "ror {c:w}, {c:w}, #15",
            "add {c:w}, {c:w}, {d:w}",
            "lsr {k:x}, {k:x}, #32",
            "add {b:w}, {b:w}, {m7:w}",
            "eor {t1:w}, {d:w}, {a:w}",
            "add {b:w}, {b:w}, {k:w}",
            "and {t1:w}, {t1:w}, {c:w}",
            "eor {t1:w}, {t1:w}, {a:w}",
            "add {b:w}, {b:w}, {t1:w}",
            "ror {b:w}, {b:w}, #10",
            "add {b:w}, {b:w}, {c:w}",
            "ldr {k:x}, [{constants}, #32]",
            "add {a:w}, {a:w}, {m8:w}",
            "eor {t1:w}, {c:w}, {d:w}",
            "add {a:w}, {a:w}, {k:w}",
            "and {t1:w}, {t1:w}, {b:w}",
            "eor {t1:w}, {t1:w}, {d:w}",
            "add {a:w}, {a:w}, {t1:w}",
            "ror {a:w}, {a:w}, #25",
            "add {a:w}, {a:w}, {b:w}",
            "lsr {k:x}, {k:x}, #32",
            "add {d:w}, {d:w}, {m9:w}",
            "eor {t1:w}, {b:w}, {c:w}",
            "add {d:w}, {d:w}, {k:w}",
            "and {t1:w}, {t1:w}, {a:w}",
            "eor {t1:w}, {t1:w}, {c:w}",
            "add {d:w}, {d:w}, {t1:w}",
            "ror {d:w}, {d:w}, #20",
            "add {d:w}, {d:w}, {a:w}",
            "ldr {k:x}, [{constants}, #40]",
            "add {c:w}, {c:w}, {m10:w}",
            "eor {t1:w}, {a:w}, {b:w}",
            "add {c:w}, {c:w}, {k:w}",
            "and {t1:w}, {t1:w}, {d:w}",
            "eor {t1:w}, {t1:w}, {b:w}",
            "add {c:w}, {c:w}, {t1:w}",
            "ror {c:w}, {c:w}, #15",
            "add {c:w}, {c:w}, {d:w}",
            "lsr {k:x}, {k:x}, #32",
            "add {b:w}, {b:w}, {m11:w}",
            "eor {t1:w}, {d:w}, {a:w}",
            "add {b:w}, {b:w}, {k:w}",
            "and {t1:w}, {t1:w}, {c:w}",
            "eor {t1:w}, {t1:w}, {a:w}",
            "add {b:w}, {b:w}, {t1:w}",
            "ror {b:w}, {b:w}, #10",
            "add {b:w}, {b:w}, {c:w}",
            "ldr {k:x}, [{constants}, #48]",
            "add {a:w}, {a:w}, {m12:w}",
            "eor {t1:w}, {c:w}, {d:w}",
            "add {a:w}, {a:w}, {k:w}",
            "and {t1:w}, {t1:w}, {b:w}",
            "eor {t1:w}, {t1:w}, {d:w}",
            "add {a:w}, {a:w}, {t1:w}",
            "ror {a:w}, {a:w}, #25",
            "add {a:w}, {a:w}, {b:w}",
            "lsr {k:x}, {k:x}, #32",
            "add {d:w}, {d:w}, {m13:w}",
            "eor {t1:w}, {b:w}, {c:w}",
            "add {d:w}, {d:w}, {k:w}",
            "and {t1:w}, {t1:w}, {a:w}",
            "eor {t1:w}, {t1:w}, {c:w}",
            "add {d:w}, {d:w}, {t1:w}",
            "ror {d:w}, {d:w}, #20",
            "add {d:w}, {d:w}, {a:w}",
            "ldr {k:x}, [{constants}, #56]",
            "add {c:w}, {c:w}, {m14:w}",
            "eor {t1:w}, {a:w}, {b:w}",
            "add {c:w}, {c:w}, {k:w}",
            "and {t1:w}, {t1:w}, {d:w}",
            "eor {t1:w}, {t1:w}, {b:w}",
            "add {c:w}, {c:w}, {t1:w}",
            "ror {c:w}, {c:w}, #15",
            "add {c:w}, {c:w}, {d:w}",
            "lsr {k:x}, {k:x}, #32",
            "add {b:w}, {b:w}, {m15:w}",
            "eor {t1:w}, {d:w}, {a:w}",
            "add {b:w}, {b:w}, {k:w}",
            "and {t1:w}, {t1:w}, {c:w}",
            "eor {t1:w}, {t1:w}, {a:w}",
            "add {b:w}, {b:w}, {t1:w}",
            "ror {b:w}, {b:w}, #10",
            "add {b:w}, {b:w}, {c:w}",
            "ldr {k:x}, [{constants}, #64]",
            "add {a:w}, {a:w}, {m1:w}",
            "bic {t1:w}, {c:w}, {d:w}",
            "add {a:w}, {a:w}, {k:w}",
            "and {t2:w}, {b:w}, {d:w}",
            "add {a:w}, {a:w}, {t1:w}",
            "add {a:w}, {a:w}, {t2:w}",
            "ror {a:w}, {a:w}, #27",
            "add {a:w}, {a:w}, {b:w}",
            "lsr {k:x}, {k:x}, #32",
            "add {d:w}, {d:w}, {m6:w}",
            "bic {t1:w}, {b:w}, {c:w}",
            "add {d:w}, {d:w}, {k:w}",
            "and {t2:w}, {a:w}, {c:w}",
            "add {d:w}, {d:w}, {t1:w}",
            "add {d:w}, {d:w}, {t2:w}",
            "ror {d:w}, {d:w}, #23",
            "add {d:w}, {d:w}, {a:w}",
            "ldr {k:x}, [{constants}, #72]",
            "add {c:w}, {c:w}, {m11:w}",
            "bic {t1:w}, {a:w}, {b:w}",
            "add {c:w}, {c:w}, {k:w}",
            "and {t2:w}, {d:w}, {b:w}",
            "add {c:w}, {c:w}, {t1:w}",
            "add {c:w}, {c:w}, {t2:w}",
            "ror {c:w}, {c:w}, #18",
            "add {c:w}, {c:w}, {d:w}",
            "lsr {k:x}, {k:x}, #32",
            "add {b:w}, {b:w}, {m0:w}",
            "bic {t1:w}, {d:w}, {a:w}",
            "add {b:w}, {b:w}, {k:w}",
            "and {t2:w}, {c:w}, {a:w}",
            "add {b:w}, {b:w}, {t1:w}",
            "add {b:w}, {b:w}, {t2:w}",
            "ror {b:w}, {b:w}, #12",
            "add {b:w}, {b:w}, {c:w}",
            "ldr {k:x}, [{constants}, #80]",
            "add {a:w}, {a:w}, {m5:w}",
            "bic {t1:w}, {c:w}, {d:w}",
            "add {a:w}, {a:w}, {k:w}",
            "and {t2:w}, {b:w}, {d:w}",
            "add {a:w}, {a:w}, {t1:w}",
            "add {a:w}, {a:w}, {t2:w}",
            "ror {a:w}, {a:w}, #27",
            "add {a:w}, {a:w}, {b:w}",
            "lsr {k:x}, {k:x}, #32",
            "add {d:w}, {d:w}, {m10:w}",
            "bic {t1:w}, {b:w}, {c:w}",
            "add {d:w}, {d:w}, {k:w}",
            "and {t2:w}, {a:w}, {c:w}",
            "add {d:w}, {d:w}, {t1:w}",
            "add {d:w}, {d:w}, {t2:w}",
            "ror {d:w}, {d:w}, #23",
            "add {d:w}, {d:w}, {a:w}",
            "ldr {k:x}, [{constants}, #88]",
            "add {c:w}, {c:w}, {m15:w}",
            "bic {t1:w}, {a:w}, {b:w}",
            "add {c:w}, {c:w}, {k:w}",
            "and {t2:w}, {d:w}, {b:w}",
            "add {c:w}, {c:w}, {t1:w}",
            "add {c:w}, {c:w}, {t2:w}",
            "ror {c:w}, {c:w}, #18",
            "add {c:w}, {c:w}, {d:w}",
            "lsr {k:x}, {k:x}, #32",
            "add {b:w}, {b:w}, {m4:w}",
            "bic {t1:w}, {d:w}, {a:w}",
            "add {b:w}, {b:w}, {k:w}",
            "and {t2:w}, {c:w}, {a:w}",
            "add {b:w}, {b:w}, {t1:w}",
            "add {b:w}, {b:w}, {t2:w}",
            "ror {b:w}, {b:w}, #12",
            "add {b:w}, {b:w}, {c:w}",
            "ldr {k:x}, [{constants}, #96]",
            "add {a:w}, {a:w}, {m9:w}",
            "bic {t1:w}, {c:w}, {d:w}",
            "add {a:w}, {a:w}, {k:w}",
            "and {t2:w}, {b:w}, {d:w}",
            "add {a:w}, {a:w}, {t1:w}",
            "add {a:w}, {a:w}, {t2:w}",
            "ror {a:w}, {a:w}, #27",
            "add {a:w}, {a:w}, {b:w}",
            "lsr {k:x}, {k:x}, #32",
            "add {d:w}, {d:w}, {m14:w}",
            "bic {t1:w}, {b:w}, {c:w}",
            "add {d:w}, {d:w}, {k:w}",
            "and {t2:w}, {a:w}, {c:w}",
            "add {d:w}, {d:w}, {t1:w}",
            "add {d:w}, {d:w}, {t2:w}",
            "ror {d:w}, {d:w}, #23",
            "add {d:w}, {d:w}, {a:w}",
            "ldr {k:x}, [{constants}, #104]",
            "add {c:w}, {c:w}, {m3:w}",
            "bic {t1:w}, {a:w}, {b:w}",
            "add {c:w}, {c:w}, {k:w}",
            "and {t2:w}, {d:w}, {b:w}",
            "add {c:w}, {c:w}, {t1:w}",
            "add {c:w}, {c:w}, {t2:w}",
            "ror {c:w}, {c:w}, #18",
            "add {c:w}, {c:w}, {d:w}",
            "lsr {k:x}, {k:x}, #32",
            "add {b:w}, {b:w}, {m8:w}",
            "bic {t1:w}, {d:w}, {a:w}",
            "add {b:w}, {b:w}, {k:w}",
            "and {t2:w}, {c:w}, {a:w}",
            "add {b:w}, {b:w}, {t1:w}",
            "add {b:w}, {b:w}, {t2:w}",
            "ror {b:w}, {b:w}, #12",
            "add {b:w}, {b:w}, {c:w}",
            "ldr {k:x}, [{constants}, #112]",
            "add {a:w}, {a:w}, {m13:w}",
            "bic {t1:w}, {c:w}, {d:w}",
            "add {a:w}, {a:w}, {k:w}",
            "and {t2:w}, {b:w}, {d:w}",
            "add {a:w}, {a:w}, {t1:w}",
            "add {a:w}, {a:w}, {t2:w}",
            "ror {a:w}, {a:w}, #27",
            "add {a:w}, {a:w}, {b:w}",
            "lsr {k:x}, {k:x}, #32",
            "add {d:w}, {d:w}, {m2:w}",
            "bic {t1:w}, {b:w}, {c:w}",
            "add {d:w}, {d:w}, {k:w}",
            "and {t2:w}, {a:w}, {c:w}",
            "add {d:w}, {d:w}, {t1:w}",
            "add {d:w}, {d:w}, {t2:w}",
            "ror {d:w}, {d:w}, #23",
            "add {d:w}, {d:w}, {a:w}",
            "ldr {k:x}, [{constants}, #120]",
            "add {c:w}, {c:w}, {m7:w}",
            "bic {t1:w}, {a:w}, {b:w}",
            "add {c:w}, {c:w}, {k:w}",
            "and {t2:w}, {d:w}, {b:w}",
            "add {c:w}, {c:w}, {t1:w}",
            "add {c:w}, {c:w}, {t2:w}",
            "ror {c:w}, {c:w}, #18",
            "add {c:w}, {c:w}, {d:w}",
            "lsr {k:x}, {k:x}, #32",
            "add {b:w}, {b:w}, {m12:w}",
            "bic {t1:w}, {d:w}, {a:w}",
            "add {b:w}, {b:w}, {k:w}",
            "and {t2:w}, {c:w}, {a:w}",
            "add {b:w}, {b:w}, {t1:w}",
            "add {b:w}, {b:w}, {t2:w}",
            "ror {b:w}, {b:w}, #12",
            "add {b:w}, {b:w}, {c:w}",
            "ldr {k:x}, [{constants}, #128]",
            "add {a:w}, {a:w}, {m5:w}",
            "eor {t1:w}, {b:w}, {c:w}",
            "add {a:w}, {a:w}, {k:w}",
            "eor {t1:w}, {t1:w}, {d:w}",
            "add {a:w}, {a:w}, {t1:w}",
            "ror {a:w}, {a:w}, #28",
            "add {a:w}, {a:w}, {b:w}",
            "lsr {k:x}, {k:x}, #32",
            "add {d:w}, {d:w}, {m8:w}",
            "eor {t1:w}, {a:w}, {b:w}",
            "add {d:w}, {d:w}, {k:w}",
            "eor {t1:w}, {t1:w}, {c:w}",
            "add {d:w}, {d:w}, {t1:w}",
            "ror {d:w}, {d:w}, #21",
            "add {d:w}, {d:w}, {a:w}",
            "ldr {k:x}, [{constants}, #136]",
            "add {c:w}, {c:w}, {m11:w}",
            "eor {t1:w}, {d:w}, {a:w}",
            "add {c:w}, {c:w}, {k:w}",
            "eor {t1:w}, {t1:w}, {b:w}",
            "add {c:w}, {c:w}, {t1:w}",
            "ror {c:w}, {c:w}, #16",
            "add {c:w}, {c:w}, {d:w}",
            "lsr {k:x}, {k:x}, #32",
            "add {b:w}, {b:w}, {m14:w}",
            "eor {t1:w}, {c:w}, {d:w}",
            "add {b:w}, {b:w}, {k:w}",
            "eor {t1:w}, {t1:w}, {a:w}",
            "add {b:w}, {b:w}, {t1:w}",
            "ror {b:w}, {b:w}, #9",
            "add {b:w}, {b:w}, {c:w}",
            "ldr {k:x}, [{constants}, #144]",
            "add {a:w}, {a:w}, {m1:w}",
            "eor {t1:w}, {b:w}, {c:w}",
            "add {a:w}, {a:w}, {k:w}",
            "eor {t1:w}, {t1:w}, {d:w}",
            "add {a:w}, {a:w}, {t1:w}",
            "ror {a:w}, {a:w}, #28",
            "add {a:w}, {a:w}, {b:w}",
            "lsr {k:x}, {k:x}, #32",
            "add {d:w}, {d:w}, {m4:w}",
            "eor {t1:w}, {a:w}, {b:w}",
            "add {d:w}, {d:w}, {k:w}",
            "eor {t1:w}, {t1:w}, {c:w}",
            "add {d:w}, {d:w}, {t1:w}",
            "ror {d:w}, {d:w}, #21",
            "add {d:w}, {d:w}, {a:w}",
            "ldr {k:x}, [{constants}, #152]",
            "add {c:w}, {c:w}, {m7:w}",
            "eor {t1:w}, {d:w}, {a:w}",
            "add {c:w}, {c:w}, {k:w}",
            "eor {t1:w}, {t1:w}, {b:w}",
            "add {c:w}, {c:w}, {t1:w}",
            "ror {c:w}, {c:w}, #16",
            "add {c:w}, {c:w}, {d:w}",
            "lsr {k:x}, {k:x}, #32",
            "add {b:w}, {b:w}, {m10:w}",
            "eor {t1:w}, {c:w}, {d:w}",
            "add {b:w}, {b:w}, {k:w}",
            "eor {t1:w}, {t1:w}, {a:w}",
            "add {b:w}, {b:w}, {t1:w}",
            "ror {b:w}, {b:w}, #9",
            "add {b:w}, {b:w}, {c:w}",
            "ldr {k:x}, [{constants}, #160]",
            "add {a:w}, {a:w}, {m13:w}",
            "eor {t1:w}, {b:w}, {c:w}",
            "add {a:w}, {a:w}, {k:w}",
            "eor {t1:w}, {t1:w}, {d:w}",
            "add {a:w}, {a:w}, {t1:w}",
            "ror {a:w}, {a:w}, #28",
            "add {a:w}, {a:w}, {b:w}",
            "lsr {k:x}, {k:x}, #32",
            "add {d:w}, {d:w}, {m0:w}",
            "eor {t1:w}, {a:w}, {b:w}",
            "add {d:w}, {d:w}, {k:w}",
            "eor {t1:w}, {t1:w}, {c:w}",
            "add {d:w}, {d:w}, {t1:w}",
            "ror {d:w}, {d:w}, #21",
            "add {d:w}, {d:w}, {a:w}",
            "ldr {k:x}, [{constants}, #168]",
            "add {c:w}, {c:w}, {m3:w}",
            "eor {t1:w}, {d:w}, {a:w}",
            "add {c:w}, {c:w}, {k:w}",
            "eor {t1:w}, {t1:w}, {b:w}",
            "add {c:w}, {c:w}, {t1:w}",
            "ror {c:w}, {c:w}, #16",
            "add {c:w}, {c:w}, {d:w}",
            "lsr {k:x}, {k:x}, #32",
            "add {b:w}, {b:w}, {m6:w}",
            "eor {t1:w}, {c:w}, {d:w}",
            "add {b:w}, {b:w}, {k:w}",
            "eor {t1:w}, {t1:w}, {a:w}",
            "add {b:w}, {b:w}, {t1:w}",
            "ror {b:w}, {b:w}, #9",
            "add {b:w}, {b:w}, {c:w}",
            "ldr {k:x}, [{constants}, #176]",
            "add {a:w}, {a:w}, {m9:w}",
            "eor {t1:w}, {b:w}, {c:w}",
            "add {a:w}, {a:w}, {k:w}",
            "eor {t1:w}, {t1:w}, {d:w}",
            "add {a:w}, {a:w}, {t1:w}",
            "ror {a:w}, {a:w}, #28",
            "add {a:w}, {a:w}, {b:w}",
            "lsr {k:x}, {k:x}, #32",
            "add {d:w}, {d:w}, {m12:w}",
            "eor {t1:w}, {a:w}, {b:w}",
            "add {d:w}, {d:w}, {k:w}",
            "eor {t1:w}, {t1:w}, {c:w}",
            "add {d:w}, {d:w}, {t1:w}",
            "ror {d:w}, {d:w}, #21",
            "add {d:w}, {d:w}, {a:w}",
            "ldr {k:x}, [{constants}, #184]",
            "add {c:w}, {c:w}, {m15:w}",
            "eor {t1:w}, {d:w}, {a:w}",
            "add {c:w}, {c:w}, {k:w}",
            "eor {t1:w}, {t1:w}, {b:w}",
            "add {c:w}, {c:w}, {t1:w}",
            "ror {c:w}, {c:w}, #16",
            "add {c:w}, {c:w}, {d:w}",
            "lsr {k:x}, {k:x}, #32",
            "add {b:w}, {b:w}, {m2:w}",
            "eor {t1:w}, {c:w}, {d:w}",
            "add {b:w}, {b:w}, {k:w}",
            "eor {t1:w}, {t1:w}, {a:w}",
            "add {b:w}, {b:w}, {t1:w}",
            "ror {b:w}, {b:w}, #9",
            "add {b:w}, {b:w}, {c:w}",
            "ldr {k:x}, [{constants}, #192]",
            "add {a:w}, {a:w}, {m0:w}",
            "orn {t1:w}, {b:w}, {d:w}",
            "add {a:w}, {a:w}, {k:w}",
            "eor {t1:w}, {t1:w}, {c:w}",
            "add {a:w}, {a:w}, {t1:w}",
            "ror {a:w}, {a:w}, #26",
            "add {a:w}, {a:w}, {b:w}",
            "lsr {k:x}, {k:x}, #32",
            "add {d:w}, {d:w}, {m7:w}",
            "orn {t1:w}, {a:w}, {c:w}",
            "add {d:w}, {d:w}, {k:w}",
            "eor {t1:w}, {t1:w}, {b:w}",
            "add {d:w}, {d:w}, {t1:w}",
            "ror {d:w}, {d:w}, #22",
            "add {d:w}, {d:w}, {a:w}",
            "ldr {k:x}, [{constants}, #200]",
            "add {c:w}, {c:w}, {m14:w}",
            "orn {t1:w}, {d:w}, {b:w}",
            "add {c:w}, {c:w}, {k:w}",
            "eor {t1:w}, {t1:w}, {a:w}",
            "add {c:w}, {c:w}, {t1:w}",
            "ror {c:w}, {c:w}, #17",
            "add {c:w}, {c:w}, {d:w}",
            "lsr {k:x}, {k:x}, #32",
            "add {b:w}, {b:w}, {m5:w}",
            "orn {t1:w}, {c:w}, {a:w}",
            "add {b:w}, {b:w}, {k:w}",
            "eor {t1:w}, {t1:w}, {d:w}",
            "add {b:w}, {b:w}, {t1:w}",
            "ror {b:w}, {b:w}, #11",
            "add {b:w}, {b:w}, {c:w}",
            "ldr {k:x}, [{constants}, #208]",
            "add {a:w}, {a:w}, {m12:w}",
            "orn {t1:w}, {b:w}, {d:w}",
            "add {a:w}, {a:w}, {k:w}",
            "eor {t1:w}, {t1:w}, {c:w}",
            "add {a:w}, {a:w}, {t1:w}",
            "ror {a:w}, {a:w}, #26",
            "add {a:w}, {a:w}, {b:w}",
            "lsr {k:x}, {k:x}, #32",
            "add {d:w}, {d:w}, {m3:w}",
            "orn {t1:w}, {a:w}, {c:w}",
            "add {d:w}, {d:w}, {k:w}",
            "eor {t1:w}, {t1:w}, {b:w}",
            "add {d:w}, {d:w}, {t1:w}",
            "ror {d:w}, {d:w}, #22",
            "add {d:w}, {d:w}, {a:w}",
            "ldr {k:x}, [{constants}, #216]",
            "add {c:w}, {c:w}, {m10:w}",
            "orn {t1:w}, {d:w}, {b:w}",
            "add {c:w}, {c:w}, {k:w}",
            "eor {t1:w}, {t1:w}, {a:w}",
            "add {c:w}, {c:w}, {t1:w}",
            "ror {c:w}, {c:w}, #17",
            "add {c:w}, {c:w}, {d:w}",
            "lsr {k:x}, {k:x}, #32",
            "add {b:w}, {b:w}, {m1:w}",
            "orn {t1:w}, {c:w}, {a:w}",
            "add {b:w}, {b:w}, {k:w}",
            "eor {t1:w}, {t1:w}, {d:w}",
            "add {b:w}, {b:w}, {t1:w}",
            "ror {b:w}, {b:w}, #11",
            "add {b:w}, {b:w}, {c:w}",
            "ldr {k:x}, [{constants}, #224]",
            "add {a:w}, {a:w}, {m8:w}",
            "orn {t1:w}, {b:w}, {d:w}",
            "add {a:w}, {a:w}, {k:w}",
            "eor {t1:w}, {t1:w}, {c:w}",
            "add {a:w}, {a:w}, {t1:w}",
            "ror {a:w}, {a:w}, #26",
            "add {a:w}, {a:w}, {b:w}",
            "lsr {k:x}, {k:x}, #32",
            "add {d:w}, {d:w}, {m15:w}",
            "orn {t1:w}, {a:w}, {c:w}",
            "add {d:w}, {d:w}, {k:w}",
            "eor {t1:w}, {t1:w}, {b:w}",
            "add {d:w}, {d:w}, {t1:w}",
            "ror {d:w}, {d:w}, #22",
            "add {d:w}, {d:w}, {a:w}",
            "ldr {k:x}, [{constants}, #232]",
            "add {c:w}, {c:w}, {m6:w}",
            "orn {t1:w}, {d:w}, {b:w}",
            "add {c:w}, {c:w}, {k:w}",
            "eor {t1:w}, {t1:w}, {a:w}",
            "add {c:w}, {c:w}, {t1:w}",
            "ror {c:w}, {c:w}, #17",
            "add {c:w}, {c:w}, {d:w}",
            "lsr {k:x}, {k:x}, #32",
            "add {b:w}, {b:w}, {m13:w}",
            "orn {t1:w}, {c:w}, {a:w}",
            "add {b:w}, {b:w}, {k:w}",
            "eor {t1:w}, {t1:w}, {d:w}",
            "add {b:w}, {b:w}, {t1:w}",
            "ror {b:w}, {b:w}, #11",
            "add {b:w}, {b:w}, {c:w}",
            "ldr {k:x}, [{constants}, #240]",
            "add {a:w}, {a:w}, {m4:w}",
            "orn {t1:w}, {b:w}, {d:w}",
            "add {a:w}, {a:w}, {k:w}",
            "eor {t1:w}, {t1:w}, {c:w}",
            "add {a:w}, {a:w}, {t1:w}",
            "ror {a:w}, {a:w}, #26",
            "add {a:w}, {a:w}, {b:w}",
            "lsr {k:x}, {k:x}, #32",
            "add {d:w}, {d:w}, {m11:w}",
            "orn {t1:w}, {a:w}, {c:w}",
            "add {d:w}, {d:w}, {k:w}",
            "eor {t1:w}, {t1:w}, {b:w}",
            "add {d:w}, {d:w}, {t1:w}",
            "ror {d:w}, {d:w}, #22",
            "add {d:w}, {d:w}, {a:w}",
            "ldr {k:x}, [{constants}, #248]",
            "add {c:w}, {c:w}, {m2:w}",
            "orn {t1:w}, {d:w}, {b:w}",
            "add {c:w}, {c:w}, {k:w}",
            "eor {t1:w}, {t1:w}, {a:w}",
            "add {c:w}, {c:w}, {t1:w}",
            "ror {c:w}, {c:w}, #17",
            "add {c:w}, {c:w}, {d:w}",
            "lsr {k:x}, {k:x}, #32",
            "add {b:w}, {b:w}, {m9:w}",
            "orn {t1:w}, {c:w}, {a:w}",
            "add {b:w}, {b:w}, {k:w}",
            "eor {t1:w}, {t1:w}, {d:w}",
            "add {b:w}, {b:w}, {t1:w}",
            "ror {b:w}, {b:w}, #11",
            "add {b:w}, {b:w}, {c:w}",
            a = inout(reg) a,
            b = inout(reg) b,
            c = inout(reg) c,
            d = inout(reg) d,
            t1 = out(reg) _,
            t2 = out(reg) _,
            k = out(reg) _,
            input = in(reg) block.as_ptr(),
            constants = in(reg) K_PAIRS.as_ptr(),
            m0 = out(reg) _,
            m1 = out(reg) _,
            m2 = out(reg) _,
            m3 = out(reg) _,
            m4 = out(reg) _,
            m5 = out(reg) _,
            m6 = out(reg) _,
            m7 = out(reg) _,
            m8 = out(reg) _,
            m9 = out(reg) _,
            m10 = out(reg) _,
            m11 = out(reg) _,
            m12 = out(reg) _,
            m13 = out(reg) _,
            m14 = out(reg) _,
            m15 = out(reg) _,
            options(nostack, readonly, preserves_flags),
        );
    }

    state[0] = initial[0].wrapping_add(a);
    state[1] = initial[1].wrapping_add(b);
    state[2] = initial[2].wrapping_add(c);
    state[3] = initial[3].wrapping_add(d);
}
